CREATE TABLE `ads_bi_quality_monitor_shipping_detail` (
  `shipping_order_code` varchar(100) DEFAULT NULL COMMENT '派车单编码',
  `license_plate` varchar(100) DEFAULT NULL COMMENT '车牌号',
  `truck_type` varchar(50) DEFAULT NULL COMMENT '车辆类型',
  `tenant_id` varchar(100) DEFAULT NULL COMMENT '租户编码',
  `tenant_name` varchar(200) DEFAULT NULL COMMENT '租户名称',
  `father_company_code` varchar(100) DEFAULT NULL COMMENT '分子公司编码',
  `father_company_name` varchar(200) DEFAULT NULL COMMENT '分子公司名称',
  `father_company_short_name` varchar(200) DEFAULT NULL COMMENT '分子公司简称',
  `start_transport_time` varchar(50) DEFAULT NULL COMMENT '运输出发时间',
  `signing_time` varchar(50) DEFAULT NULL COMMENT '派车单签收时间',
  `plan_start_time` varchar(50) DEFAULT NULL COMMENT '派车单计划取货时间',
  `plan_end_time` varchar(50) DEFAULT NULL COMMENT '派车单计划送达时间',
  `frist_fence_time` varchar(50) DEFAULT NULL COMMENT '第一次碰撞装货地电子围栏时间',
  `leave_load_station_2km_time` varchar(50) DEFAULT NULL COMMENT '离开最后一个装货地电子围栏2km的时间',
  `frist_arrive_unload_time` varchar(50) DEFAULT NULL COMMENT '首次到达卸货点电子围栏时间',
  `transport_type` varchar(10) DEFAULT NULL COMMENT '运输类型(干线/城配)',
  `plan_mileage` varchar(50) DEFAULT NULL COMMENT '计划里程',
  `driver_accept_time` varchar(50) DEFAULT NULL COMMENT '司机接单时间',
  `driver_name` varchar(50) DEFAULT NULL COMMENT '司机姓名',
  `driver_phone` varchar(50) DEFAULT NULL COMMENT '司机电话',
  `driver_type` varchar(10) DEFAULT NULL COMMENT '司机类型',
  `transport_tenant_id` varchar(100) DEFAULT NULL COMMENT '运力承运商id',
  `transport_tenant_name` varchar(200) DEFAULT NULL COMMENT '运力承运商名称',
  `warm_area` varchar(50) DEFAULT NULL COMMENT '温区信息',
  `waybill_count` int DEFAULT NULL COMMENT '运单数量',
  `gps_device_list` varchar(100) DEFAULT NULL COMMENT 'gps设备',
  `gps_report_dot_num` int DEFAULT NULL COMMENT 'gps上报点数',
  `temp_substandard_min` decimal(20,8) DEFAULT NULL COMMENT '温度不达标时长(分钟)',
  `temp_substandard_min_n12` decimal(20,8) DEFAULT NULL COMMENT '温度不达标时长(分钟)_-12',
  `temp_substandard_min_n16` decimal(20,8) DEFAULT NULL COMMENT '温度不达标时长(分钟)_-16',
  `shipping_order_transport_min` decimal(20,8) DEFAULT NULL COMMENT '派车单运输总时长(分钟)',
  `shipping_order_temp_standard_rate` decimal(20,8) DEFAULT NULL COMMENT '派车单温度达标率',
  `shipping_order_temp_standard_rate_n12` decimal(20,8) DEFAULT NULL COMMENT '派车单温度达标率_-12',
  `shipping_order_temp_standard_rate_n16` decimal(20,8) DEFAULT NULL COMMENT '派车单温度达标率_-16',
  `dep_fence_match_num` int DEFAULT NULL COMMENT '出发地电子围栏匹配数量',
  `dep_total_num` int DEFAULT NULL COMMENT '出发地总数量',
  `dep_fence_match_rate` decimal(20,8) DEFAULT NULL COMMENT '出发地电子围栏匹配率',
  `des_fence_match_num` int DEFAULT NULL COMMENT '目的地电子围栏匹配数量',
  `des_total_num` int DEFAULT NULL COMMENT '目的地总数量',
  `des_fence_match_rate` decimal(20,8) DEFAULT NULL COMMENT '目的地电子围栏匹配率',
  `exception_shipping_order_type` varchar(10) DEFAULT NULL COMMENT '异常派车单情况,0-非异常',
  `settlement_tenant_id` varchar(100) DEFAULT NULL COMMENT '结算主体租户id',
  `settlement_tenant_name` varchar(100) DEFAULT NULL COMMENT '结算主体租户名称',
  `truck_ownership` varchar(100) DEFAULT NULL COMMENT '车辆所有权(自有/外请/临时)',
  `load_finish_time` varchar(50) DEFAULT NULL COMMENT '派车单点击装货完成时间',
  `last_leave_unload_time` varchar(50) DEFAULT NULL COMMENT '最后离开卸货点时间',
  `temp_right_tag` varchar(20) DEFAULT NULL COMMENT '温度是否合格(合格/不合格/不参与评估)',
  `warm_area_type` varchar(20) DEFAULT NULL COMMENT '温区类型。常温/冷链/自定义区间',
  `source_dt` varchar(20) DEFAULT NULL COMMENT '派车单来源的增量表dt',
  `cur_shipping_odr_cust` text COMMENT '当前派车单对应的客户',
  `is_app_operation` varchar(10) DEFAULT NULL COMMENT '是否APP操作卡控',
  `leave_load_station_time_app` varchar(50) DEFAULT NULL COMMENT '离开第一个装货地时间_app',
  `frist_arrive_unload_time_app` varchar(50) DEFAULT NULL COMMENT '到达第一个卸货点时间_app',
  `last_arrive_unload_time_app` varchar(50) DEFAULT NULL COMMENT '到达最后一个卸货点时间_app',
  `temp_calc_start_time` varchar(50) DEFAULT NULL COMMENT '温度计算开始时间',
  `temp_calc_end_time` varchar(50) DEFAULT NULL COMMENT '温度计算结束时间',
  `exception_shipping_order_type_desc` varchar(100) DEFAULT NULL COMMENT '异常派车单情况描述',
  `root_shipping_odr_cust` text COMMENT '根派车单对应的客户',
  `is_use_custom_temp_range` varchar(10) DEFAULT NULL COMMENT '是否使用自定义温度范围',
  `temp_eval_lowest` int DEFAULT NULL COMMENT '温度考核最低值',
  `temp_eval_highest` int DEFAULT NULL COMMENT '温度考核最高值',
  `is_gps_cover` varchar(10) DEFAULT NULL COMMENT 'GPS是否覆盖',
  `shipping_create_time` varchar(50) DEFAULT NULL COMMENT '派车单创建时间',
  `gps_device_list_plan` varchar(100) DEFAULT NULL COMMENT 'GPS设备_预估',
  `is_gps_cover_plan` varchar(10) DEFAULT NULL COMMENT 'GPS是否覆盖_预估',
  `first_station_is_on_time` varchar(10) DEFAULT NULL COMMENT '首店是否准时',
  `is_many_warm` varchar(10) DEFAULT NULL COMMENT '是否多温区',
  `many_temp_standard_rate` decimal(20,8) DEFAULT NULL COMMENT '多温区温度达标率',
  `lc_standard_ratio` decimal(20,8) DEFAULT NULL COMMENT '冷藏温度达标率',
  `ld_standard_ratio` decimal(20,8) DEFAULT NULL COMMENT '冷冻温度达标率',
  `probe_warm_list` text COMMENT '探头温区',
  `lc_right_tag` varchar(20) DEFAULT NULL COMMENT '冷藏是否合格',
  `ld_right_tag` varchar(20) DEFAULT NULL COMMENT '冷冻是否合格',
  `root_project_name_list` text COMMENT '根项目名称',
  KEY `idx_shipping_code` (`shipping_order_code`),
  KEY `idx_sdt` (`source_dt`),
  KEY `fk_license_plate` (`license_plate`),
  CONSTRAINT `fk_license_plate` FOREIGN KEY (`license_plate`) REFERENCES `dim_pub_truck_info` (`license_plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='BI看板_品质监控_派车单明细';

CREATE TABLE `ads_customer_portrait_index_sum_da` (
  `customer_code` varchar(100) DEFAULT NULL COMMENT '货主编码',
  `customer_all_name` varchar(200) DEFAULT NULL COMMENT '企业名称',
  `customer_name` varchar(200) DEFAULT NULL COMMENT '货主简称',
  `uniform_credit_code` varchar(100) DEFAULT NULL COMMENT '企业信用代码',
  `customer_type_newhope` varchar(50) DEFAULT NULL COMMENT '货主类型集团内外(六和/厚生/新乳业/草根知本)',
  `customer_group_short_name` varchar(100) DEFAULT NULL COMMENT '品牌',
  `create_time` varchar(50) DEFAULT NULL COMMENT '创建时间',
  `contacts` varchar(100) DEFAULT NULL COMMENT '货主-联系人',
  `tel_phone` varchar(100) DEFAULT NULL COMMENT '货主-联系电话',
  `station_cnt` varchar(100) DEFAULT NULL COMMENT '货主系统录入站点数',
  `is_effective_contract` varchar(10) DEFAULT NULL COMMENT '有无有效合同：有/无',
  `industry_type` text COMMENT '货主-行业列表',
  `customer_type_product` text COMMENT '货主-产品类型列表',
  `customer_type` varchar(10) DEFAULT NULL COMMENT '货主-类型-个人/企业',
  `status` varchar(10) DEFAULT NULL COMMENT '货主-状态：已创建/待通过/已绑定/移除绑定/待提交/淘汰/删除',
  `real_name_status` varchar(10) DEFAULT NULL COMMENT '企业-认证状态：已认证/未认证/认证失败',
  `cooperative_nature` varchar(10) DEFAULT NULL COMMENT '货主-合约/临时',
  `legal_person` varchar(100) DEFAULT NULL COMMENT '企业-法人姓名',
  `company_adress` text COMMENT '企业-地址',
  `registered_capital` varchar(100) DEFAULT NULL COMMENT '企业-注册资金',
  `business_scope` text COMMENT '企业-经营范围',
  `employee_scale` varchar(20) DEFAULT NULL COMMENT '企业-人员规模',
  `legal_telephone` varchar(100) DEFAULT NULL COMMENT '企业-法人电话',
  `register_address_longitude` varchar(20) DEFAULT NULL COMMENT '企业-注册地经度',
  `register_address_latitude` varchar(20) DEFAULT NULL COMMENT '企业-注册地纬度',
  `register_province` varchar(100) DEFAULT NULL COMMENT '企业-注册省份',
  `register_city` varchar(100) DEFAULT NULL COMMENT '企业-注册城市',
  `register_city_longitude` varchar(20) DEFAULT NULL COMMENT '企业-注册城市经度',
  `register_city_latitude` varchar(20) DEFAULT NULL COMMENT '企业-注册城市纬度',
  `register_county` varchar(20) DEFAULT NULL COMMENT '企业-注册区县',
  `order_cnt_total` varchar(10) DEFAULT NULL COMMENT '累计运输订单量',
  `order_cnt_last365d` varchar(10) DEFAULT NULL COMMENT '近一年运输订单量',
  `order_cnt_last90d` varchar(10) DEFAULT NULL COMMENT '近90天运输订单量',
  `order_cnt_last30d` varchar(10) DEFAULT NULL COMMENT '近30天运输订单量',
  `order_gx_total` varchar(10) DEFAULT NULL COMMENT '累计干线运输订单量',
  `order_gx_last365d` varchar(10) DEFAULT NULL COMMENT '近一年干线运输订单量',
  `order_gx_last90d` varchar(10) DEFAULT NULL COMMENT '近90天干线运输订单量',
  `order_gx_last30d` varchar(10) DEFAULT NULL COMMENT '近30天干线运输订单量',
  `order_cp_total` varchar(10) DEFAULT NULL COMMENT '累计城配运输订单量',
  `order_cp_last365d` varchar(10) DEFAULT NULL COMMENT '近一年城配运输订单量',
  `order_cp_last90d` varchar(10) DEFAULT NULL COMMENT '近90天城配运输订单量',
  `order_cp_last30d` varchar(10) DEFAULT NULL COMMENT '近30天城配运输订单量',
  `singing_time_last` varchar(50) DEFAULT NULL COMMENT '最近承运时间',
  `singing_time_first` varchar(50) DEFAULT NULL COMMENT '最早承运时间',
  `des_station_total` varchar(10) DEFAULT NULL COMMENT '累计配送站点数',
  `des_station_last365d` varchar(10) DEFAULT NULL COMMENT '近365天配送站点数',
  `des_station_last90d` varchar(10) DEFAULT NULL COMMENT '近90天配送站点数',
  `des_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天配送站点数',
  `des_cp_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天城配配送站点数',
  `des_gx_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天干线配送站点数',
  `des_cp_citise_last30d` varchar(10) DEFAULT NULL COMMENT '近30天城配配送城市数',
  `des_gx_lines_last30d` varchar(10) DEFAULT NULL COMMENT '近30天干线配送线路数',
  `des_citise_last30d` varchar(10) DEFAULT NULL COMMENT '近30天配送城市数',
  `dep_station_total` varchar(10) DEFAULT NULL COMMENT '累计出发站点数',
  `dep_station_last365d` varchar(10) DEFAULT NULL COMMENT '近365天出发站点数',
  `dep_station_last90d` varchar(10) DEFAULT NULL COMMENT '近90天出发站点数',
  `dep_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天出发站点数',
  `dep_cp_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天城配出发站点数',
  `dep_gx_station_last30d` varchar(10) DEFAULT NULL COMMENT '近30天干线出发站点数',
  `weight_last30d` varchar(10) DEFAULT NULL COMMENT '近30天单均配送重量',
  `weight_cp_last30d` varchar(10) DEFAULT NULL COMMENT '近30天城配单均配送重量',
  `weight_gx_last30d` varchar(10) DEFAULT NULL COMMENT '近30天干线单均配送重量',
  `is_48_audit` varchar(10) DEFAULT NULL COMMENT '近30天稽核及时率',
  `is_on_time` varchar(10) DEFAULT NULL COMMENT '近30天准时送达率',
  `is_on_dep` varchar(10) DEFAULT NULL COMMENT '近30天准时取货率',
  `is_gps_cover` varchar(10) DEFAULT NULL COMMENT '近30天gps覆盖率',
  `temp_right_tag` varchar(10) DEFAULT NULL COMMENT '近30天温度达标率',
  `gx_line` text COMMENT '近30天干线常配送线路',
  `cp_line` text COMMENT '近30天城配常配送线路',
  `station_name` text COMMENT '近30天常配送站点',
  `father_tenant_name` text COMMENT '近30天常合作承运商',
  `tax_incom_total` varchar(10) DEFAULT NULL COMMENT '累计运输收入/元',
  `tax_incom_last365d` varchar(10) DEFAULT NULL COMMENT '近365天运输收入/元',
  `tax_incom_last90d` varchar(10) DEFAULT NULL COMMENT '近90天运输收入/元',
  `tax_incom_last30d` varchar(10) DEFAULT NULL COMMENT '近30天运输收入/元',
  `gx_goods` text COMMENT '近30天干线常配送货品',
  `cp_goods` text COMMENT '近30天城配常配送货品',
  `customer_behavior` varchar(20) DEFAULT NULL COMMENT '待激活：历史无单；新增：近一年新增下单客户；活跃：近一年有单且下单历史超过一年；沉默：近一年未下单的客户',
  `ck_order_last365d` varchar(10) DEFAULT NULL COMMENT '近一年出入库单',
  `receipt_ck_last365d` varchar(10) DEFAULT NULL COMMENT '近一年入库单',
  `deliver_order_last365d` varchar(10) DEFAULT NULL COMMENT '近一年出库单量'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='货主画像统计表';

CREATE TABLE `ads_truck_portrait_index_sum_da` (
  `truck_id` varchar(100) DEFAULT NULL COMMENT '车辆id',
  `license_plate` varchar(100) DEFAULT NULL COMMENT '车牌号',
  `license_plate_orig` varchar(100) DEFAULT NULL COMMENT '原始车牌号',
  `license_plate_color` varchar(30) DEFAULT NULL COMMENT '车牌颜色:黄色,绿色,蓝色,渐变绿,其他',
  `is_cold_chain_car` varchar(10) DEFAULT NULL COMMENT '是否冷链车',
  `temperature_probe` int DEFAULT NULL COMMENT '登记温度探头数',
  `oil_card_no` varchar(100) DEFAULT NULL COMMENT '油卡号',
  `province` varchar(100) DEFAULT NULL COMMENT '车牌归属省份',
  `city` varchar(100) DEFAULT NULL COMMENT '车牌归属城市',
  `truck_owning_name` varchar(100) DEFAULT NULL COMMENT '车辆所有人（行驶证上的挂靠公司或个人）',
  `charge_person_phone` varchar(100) DEFAULT NULL COMMENT '联系号码',
  `box_length_std` varchar(20) DEFAULT NULL COMMENT '车长',
  `consumption_type_name` varchar(20) DEFAULT NULL COMMENT '能耗类型:天然气,电动,汽油,柴油',
  `emission_std` varchar(20) DEFAULT NULL COMMENT '标准排放:国一,国二,国三,国四,国五,国六,国七,电动,其他',
  `ttl_truck_quantity` varchar(10) DEFAULT NULL COMMENT '车辆总质量(KG)',
  `user_status` varchar(10) DEFAULT NULL COMMENT '车辆使用状态:停用、启用',
  `temperature_area` varchar(10) DEFAULT NULL COMMENT '温区:单温,双温,三温',
  `truck_load_std` varchar(10) DEFAULT NULL COMMENT '标准载重(KG)',
  `register_date` varchar(30) DEFAULT NULL COMMENT '车辆注册登记日期',
  `paperwork_date` varchar(30) DEFAULT NULL COMMENT '发证日期',
  `ad_name` varchar(200) DEFAULT NULL COMMENT '车体广告公司名称',
  `truck_volume_std` varchar(10) DEFAULT NULL COMMENT '标准容积（立方米）',
  `is_bd_system` varchar(10) DEFAULT NULL COMMENT '北斗设备是否上报定位',
  `is_jy_system` varchar(10) DEFAULT NULL COMMENT '捷依设备是否上报定位',
  `is_e6_system` varchar(10) DEFAULT NULL COMMENT '易流设备是否上报定位',
  `gps_code` varchar(100) DEFAULT NULL COMMENT 'GPS终端编码（分子公司维护）',
  `gps_system_name` varchar(100) DEFAULT NULL COMMENT 'GPS系统（分子公司维护）',
  `max_gpstime_gps` varchar(50) DEFAULT NULL COMMENT 'GPS最近定位上传时间',
  `province_name_gps` varchar(50) DEFAULT NULL COMMENT 'GPS最近定位上传时间',
  `city_name_gps` varchar(100) DEFAULT NULL COMMENT 'GPS最近定位城市',
  `district_name_gps` varchar(100) DEFAULT NULL COMMENT 'GPS最近定位区县',
  `max_gpstime_app` varchar(100) DEFAULT NULL COMMENT 'APP最近定位上传时间',
  `province_name_app` varchar(50) DEFAULT NULL COMMENT 'APP最近定位上传时间',
  `city_name_app` varchar(100) DEFAULT NULL COMMENT 'APP最近定位城市',
  `district_name_app` varchar(100) DEFAULT NULL COMMENT 'APP最近定位区县',
  `order_total_type` varchar(100) DEFAULT NULL COMMENT '累计派单量分层',
  `order_last365d_type` varchar(100) DEFAULT NULL COMMENT '近一年运输单量分层',
  `order_last90d_type` varchar(100) DEFAULT NULL COMMENT '近90天运输单量分层',
  `order_last30d_type` varchar(100) DEFAULT NULL COMMENT '近30天运输单量分层',
  `miles_total_type` varchar(100) DEFAULT NULL COMMENT '累计里程分层',
  `miles_last365d_type` varchar(100) DEFAULT NULL COMMENT '近一年运输里程分层',
  `miles_last90d_type` varchar(100) DEFAULT NULL COMMENT '近90天运输里程数分层',
  `miles_last30d_type` varchar(100) DEFAULT NULL COMMENT '近30天运输里程数分层',
  `driver_total_type` varchar(100) DEFAULT NULL COMMENT '累计承运司机数分层',
  `driver_last365_type` varchar(100) DEFAULT NULL COMMENT '近一年承运司机数分层',
  `driver_last90d_type` varchar(100) DEFAULT NULL COMMENT '近90天承运司机数分层',
  `driver_last30d_type` varchar(100) DEFAULT NULL COMMENT '近30天承运司机数分层',
  `driver_code_last` varchar(100) DEFAULT NULL COMMENT '最近承运司机',
  `driver_code_first` varchar(100) DEFAULT NULL COMMENT '最早承运司机',
  `create_time_last` varchar(100) DEFAULT NULL COMMENT '最近承运时间',
  `create_time_first` varchar(100) DEFAULT NULL COMMENT '最早承运时间',
  `cost_total_type` varchar(100) DEFAULT NULL COMMENT '累计应付金额分层',
  `cost_last365d_type` varchar(100) DEFAULT NULL COMMENT '近一年应付金额分层',
  `cost_last90d_type` varchar(100) DEFAULT NULL COMMENT '近90天应付金额分层',
  `cost_last30d_type` varchar(100) DEFAULT NULL COMMENT '近30天应付金额分层',
  `lines_total_type` varchar(100) DEFAULT NULL COMMENT '累计线路数分层',
  `lines_365d_type` varchar(100) DEFAULT NULL COMMENT '近一年线路数分层',
  `lines_90d_type` varchar(100) DEFAULT NULL COMMENT '近90天线路数分层',
  `lines_30d_type` varchar(100) DEFAULT NULL COMMENT '近30天线路数分层',
  `station_total_type` varchar(100) DEFAULT NULL COMMENT '累计到达站点数分层',
  `station_last365d_type` varchar(100) DEFAULT NULL COMMENT '近365天到达站点数分层',
  `station_last90d_type` varchar(100) DEFAULT NULL COMMENT '近90天到达站点数分层',
  `station_last30d_type` varchar(100) DEFAULT NULL COMMENT '近30天到达站点数分层',
  `is_gps_7d` varchar(20) DEFAULT NULL COMMENT '近7天是否有gps上报',
  `probe_num_max` int DEFAULT NULL COMMENT '近7天上报温度最多探头数',
  `probe_num_min` int DEFAULT NULL COMMENT '近7天上报温度最少探头数',
  `truck_type` varchar(100) DEFAULT NULL COMMENT '车型',
  `create_time` varchar(50) DEFAULT NULL COMMENT '创建时间',
  `review_status` varchar(50) DEFAULT NULL COMMENT '认证状态:已认证/未认证/无需认证',
  `stop_type` varchar(20) DEFAULT NULL COMMENT '停用类型：事故/其他',
  `stop_reason` text COMMENT '停用原因',
  `transport_status` varchar(20) DEFAULT NULL COMMENT '运输状态:运输/空闲',
  `brand_model` varchar(100) DEFAULT NULL COMMENT '品牌型号',
  `is_trailer` varchar(100) DEFAULT NULL COMMENT '机车/挂车',
  `box_brand` varchar(100) DEFAULT NULL COMMENT '车厢品牌',
  `refrigerator_brand` varchar(100) DEFAULT NULL COMMENT '冷机品牌',
  `is_refrigerator_independence` varchar(10) DEFAULT NULL COMMENT '是否独立冷机:是/否',
  `temperature` varchar(100) DEFAULT NULL COMMENT '制冷区间',
  `truck_age` varchar(10) DEFAULT NULL COMMENT '车龄',
  `truck_tenant_type` varchar(20) DEFAULT NULL COMMENT '外请、自有、个体列表',
  `is_own` varchar(10) DEFAULT NULL COMMENT '是否自有车：是/否',
  `tenant_id` varchar(100) DEFAULT NULL COMMENT '自有车租户id',
  `tenant_name` varchar(200) DEFAULT NULL COMMENT '自有车租户名称',
  `father_tenant_id` varchar(100) DEFAULT NULL COMMENT '自有车父级租户id',
  `father_tenant_name` varchar(200) DEFAULT NULL COMMENT '自有车父级租户名称',
  `own_lon` varchar(100) DEFAULT NULL COMMENT '自有车分公司停靠经度',
  `own_lat` varchar(100) DEFAULT NULL COMMENT '自有车分公司停靠纬度',
  `own_addr` text COMMENT '自有车分公司停靠地址',
  `score_star` varchar(10) DEFAULT NULL COMMENT '星级',
  `company_list` text COMMENT '车辆所属内部分公司列表',
  `driver_name_last` varchar(50) DEFAULT NULL COMMENT '最近承运司机姓名',
  `driver_name_first` varchar(50) DEFAULT NULL COMMENT '最早承运司机姓名',
  `driver_phone_last` varchar(50) DEFAULT NULL COMMENT '最近承运司机电话',
  `driver_phone_first` varchar(50) DEFAULT NULL COMMENT '最早承运司机电话',
  `lines_top5` text COMMENT '近30天干线top5线路',
  `dep_city_top5` text COMMENT '近30天城配top5城市',
  `is_ylz_driver` varchar(10) DEFAULT NULL COMMENT '车牌被绑定个体司机是否运荔枝司机',
  `company_trucktype` varchar(20) DEFAULT NULL COMMENT '鲜生活车辆类型列表：自有/外请/个体',
  `businessinsuranceendtime` varchar(50) DEFAULT NULL COMMENT '车辆商业险到期剩余时间（个体车辆）',
  `axes` int DEFAULT NULL COMMENT '轴数',
  `truck_length` decimal(20,2) DEFAULT NULL COMMENT '外廓车长',
  `truck_wide` decimal(20,2) DEFAULT NULL COMMENT '外廓车宽',
  `truck_height` decimal(20,2) DEFAULT NULL COMMENT '外廓车高',
  `truck_quantity_type` varchar(30) DEFAULT NULL COMMENT '车辆大小分类',
  `gps_mileage_last30d` varchar(20) DEFAULT NULL COMMENT '近30天gps设备上报行驶里程',
  `gps_mileage_last90d` varchar(20) DEFAULT NULL COMMENT '近90天gps设备上报行驶里程',
  `gps_days_last30d` varchar(10) DEFAULT NULL COMMENT '近30天gps设备上报行驶天数',
  `gps_days_last90d` varchar(10) DEFAULT NULL COMMENT '近90天gps设备上报行驶天数',
  `gps_avgmileage_last30d` varchar(20) DEFAULT NULL COMMENT '近30天gps设备上报行驶平均里程/天',
  `gps_avgmileage_last90d` varchar(20) DEFAULT NULL COMMENT '近90天gps设备上报行驶平均里程/天',
  `is_wide_body` varchar(10) DEFAULT NULL COMMENT '是否宽体',
  `box_wide` decimal(20,2) DEFAULT NULL COMMENT '车厢宽',
  `box_height` decimal(20,2) DEFAULT NULL COMMENT '车厢高',
  `pass_qualification_province_name` varchar(100) DEFAULT NULL COMMENT '通行资质省name',
  `pass_qualification_city_name` varchar(100) DEFAULT NULL COMMENT '通行资质市name',
  `pass_qualification_area_name` varchar(100) DEFAULT NULL COMMENT '通行资质区name',
  `car_kit_name` varchar(200) DEFAULT NULL COMMENT '车载装备名称',
  `load_accessories` varchar(200) DEFAULT NULL COMMENT '改装信息',
  `standard_truck_type` varchar(100) DEFAULT NULL COMMENT '标准车型',
  `car_floor_air_uide` varchar(10) DEFAULT NULL COMMENT '是否有导风槽',
  `is_tem_device` varchar(10) DEFAULT NULL COMMENT '是否有温控设备',
  `exchange_cnt` varchar(10) DEFAULT NULL COMMENT '积分商城兑换次数'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆画像表';

CREATE TABLE `dim_customer_enterprise_station_base_info` (
  `uniform_credit_code` text COMMENT '客户企业统一信用代码',
  `corp_name` text COMMENT '客户企业名称',
  `station_code` text COMMENT '站点编码',
  `station_name` text COMMENT '站点名称',
  `station_type` text COMMENT '站点类型',
  `station_poi` text COMMENT '站点poi',
  `station_longitude` decimal(20,8) DEFAULT NULL COMMENT '站点经度',
  `station_latitude` decimal(20,8) DEFAULT NULL COMMENT '站点纬度',
  `station_address` text COMMENT '站点地址',
  `station_province` text COMMENT '站点所在省',
  `station_city` text COMMENT '站点所在市',
  `station_county` text COMMENT '站点所在区/县',
  `delete_status` text COMMENT '删除状态',
  `enable_status` text COMMENT '启用状态',
  `crawl_status` int DEFAULT NULL COMMENT '0-纯内部站点，1-内部+爬取共同站点，2-纯爬取站点',
  `customer_group_code` text COMMENT '客户企业总部简称',
  `customer_group_name` text COMMENT '品牌名称',
  `station_brand_type` text COMMENT '站点品牌类型(0-内部客户站点，1-内部品牌站点，2-外部品牌站点)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户企业站点基础信息表';

CREATE TABLE `dim_gaode_city_info_v2` (
  `geo_region_name` text COMMENT '地理大区名称',
  `biz_region_name` text COMMENT '业务大区名称',
  `province_code` text COMMENT '高德省份code',
  `city_code` text COMMENT '高德城市code',
  `adcode` text COMMENT 'code',
  `name` text COMMENT '名称',
  `short_name` text COMMENT '简称',
  `level` text COMMENT '层级（country/region/province/city/district/street）',
  `lon` decimal(20,6) DEFAULT NULL COMMENT '中心点经度',
  `lat` decimal(20,6) DEFAULT NULL COMMENT '中心点纬度',
  `province_name` text COMMENT '省份名称',
  `province_short_name` text COMMENT '省份简称',
  `province_lon` decimal(20,6) DEFAULT NULL COMMENT '省份中心点经度',
  `province_lat` decimal(20,6) DEFAULT NULL COMMENT '省份中心点纬度',
  `city_name` text COMMENT '城市名称',
  `city_short_name` text COMMENT '城市简称',
  `city_lon` decimal(20,6) DEFAULT NULL COMMENT '城市中心点经度',
  `city_lat` decimal(20,6) DEFAULT NULL COMMENT '城市中心点纬度'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='高德行政区域表v2';

CREATE TABLE `dim_pub_truck_info` (
  `source` text COMMENT '车辆信息来源,可忽略',
  `license_plate` text COMMENT '车牌号',
  `license_plate_orig` text COMMENT '原始车牌号(未清洗车牌号)',
  `license_plate_color` text COMMENT '号牌颜色',
  `trailer_id` text COMMENT '挂车车牌号主键',
  `trailer_plate` text COMMENT '挂车车牌号名',
  `oil_card_no` text COMMENT '油卡号码',
  `etc_code_no` text COMMENT 'ETC号码',
  `is_owning_ad` text COMMENT '是否有广告',
  `truck_type_setting_id` text COMMENT '车型配置id',
  `truck_type_setting_name` text COMMENT '车型配置名称',
  `truck_type` text COMMENT '车型',
  `truck_nature` text COMMENT '车辆性质',
  `box_length` decimal(20,6) DEFAULT NULL COMMENT '车厢长(米)',
  `box_length_std` text COMMENT '标准车厢长(米)（大数据维护）',
  `box_wide` decimal(20,6) DEFAULT NULL COMMENT '车厢宽',
  `box_height` decimal(20,6) DEFAULT NULL COMMENT '车厢高',
  `truck_length` decimal(20,6) DEFAULT NULL COMMENT '外廓车长',
  `truck_wide` decimal(20,6) DEFAULT NULL COMMENT '外廓车宽',
  `truck_height` decimal(20,6) DEFAULT NULL COMMENT '外廓车高',
  `truck_load` decimal(20,6) DEFAULT NULL COMMENT '核定载重(KG）',
  `truck_load_std` text COMMENT '标准载重(KG）（大数据维护）',
  `ttl_truck_quantity` decimal(20,6) DEFAULT NULL COMMENT '车辆总质量(KG)',
  `truck_volume` decimal(20,6) DEFAULT NULL COMMENT '车厢容积（立方米）',
  `truck_volume_std` text COMMENT '标准容积（立方米）（大数据维护）',
  `truck_age` bigint DEFAULT NULL COMMENT '车龄（月）',
  `is_bd_system` text COMMENT '是否安装北斗设备',
  `is_jy_system` text COMMENT '是否安装捷依设备',
  `is_e6_system` text COMMENT '是否安装易流设备',
  `brand_model` text COMMENT '品牌型号',
  `frame_no` text COMMENT '车架号',
  `license_plate_model` text COMMENT '车牌型号',
  `engine_no` text COMMENT '发动机号',
  `tenant_id` text COMMENT '租户编码',
  `tenant_name` text COMMENT '租户名称',
  `create_user` text COMMENT '创建人',
  `truck_owning_code` text COMMENT '车辆所有人编码',
  `truck_owning_name` text COMMENT '车辆所有人（行驶证上的挂靠公司或个人）',
  `charge_person_name` text COMMENT '车辆资产负责人',
  `charge_person_phone` text COMMENT '联系电话',
  `owner_tenant_id` text COMMENT '自有关系租户编码',
  `owner_tenant_name` text COMMENT '自有关系租户名称',
  `owner_tenant_name_type` text COMMENT '自有关系公司性质（内部/外部）',
  `transport_permit_no` text COMMENT '道路运输许可证号',
  `city_paperwork` text COMMENT '入城证',
  `gps_code` text COMMENT 'GPS终端编码（分子公司维护）',
  `gps_system_name` text COMMENT 'GPS系统（分子公司维护）',
  `review_status` text COMMENT '审核状态',
  `enable_status` text COMMENT '启用状态',
  `stop_type` text COMMENT '停用类型',
  `stop_reason` text COMMENT '停用原因',
  `user_status` text COMMENT '车辆状态（启用和停用）',
  `platform_certification` text COMMENT '网络货运标识（是/否）',
  `truck_owner_ship_v0` text COMMENT '车辆自有关系（自有车/外请车）',
  `truck_owner_ship` text COMMENT '车辆自有关系（自购/自租）',
  `lease_status` text COMMENT '融资租赁状态(0: 否 1: 是)',
  `transport_status` text COMMENT '运输状态',
  `annual_review_status` bigint DEFAULT NULL COMMENT '年审状态',
  `register_date` text COMMENT '车辆注册登记日期',
  `paperwork_date` text COMMENT '发证日期',
  `vehicle_license_org` text COMMENT '发证机关',
  `annual_review_date` text COMMENT '年检时间',
  `annual_review_end_date` text COMMENT '年检有效期',
  `create_time` text COMMENT '创建时间',
  `update_time` text COMMENT '修改时间',
  `opera_time` text COMMENT '启用/停用时间',
  `consumption_type_name` text COMMENT '能耗类型',
  `refrigerator_brand` text COMMENT '冷机品牌',
  `box_brand` text COMMENT '车厢品牌',
  `emission_std` text COMMENT '排放标准',
  `temperature_area` text COMMENT '温区',
  `is_refrigerator_independence` text COMMENT '是否独立冷机',
  `is_temperature_control` text COMMENT '是否为温控设备',
  `min_temperature` decimal(20,6) DEFAULT NULL COMMENT '最低制冷温度（摄氏度）',
  `max_temperature` decimal(20,6) DEFAULT NULL COMMENT '最高制冷温度（摄氏度）',
  `tank_volume` decimal(20,6) DEFAULT NULL COMMENT '油箱容量（L）',
  `pass_qualification_code` text COMMENT '通行资质code',
  `pass_qualification_name` text COMMENT '通行资质name',
  `pass_qualification_province_code` text COMMENT '通行资质省code',
  `pass_qualification_province_name` text COMMENT '通行资质省name',
  `pass_qualification_city_code` text COMMENT '通行资质市code',
  `pass_qualification_city_name` text COMMENT '通行资质市name',
  `pass_qualification_area_code` text COMMENT '通行资质区code',
  `pass_qualification_area_name` text COMMENT '通行资质区name',
  `ad_name` text COMMENT '车体广告公司名称',
  `real_consumption` decimal(20,6) DEFAULT NULL COMMENT '实际能耗（升或度/百公里）',
  `estimate_consumption` decimal(20,6) DEFAULT NULL COMMENT '经验预估能耗（升或度/百公里）',
  `license_plate_normol_tag` text COMMENT '车牌号是否异常',
  `owning_side_name_normol_tag` text COMMENT '车辆所有人（行驶证上的挂靠公司或个人）是否异常',
  `frame_no_normol_tag` text COMMENT '车架号是否异常',
  `vehiclelicenseorg_normol_tag` text COMMENT '发证机关是否异常',
  `ttl_truck_quantity_normol_tag` text COMMENT '发证机关是否异常',
  `truck_load_normol_tag` text COMMENT '核定载重是否异常',
  `transport_permit_no_normol_tag` text COMMENT '道路运输许可证号是否异常',
  `truck_id` text COMMENT '车辆id',
  `license_plate_type_name` text COMMENT '号牌种类名称',
  `buy_date` text COMMENT '车辆购买日期',
  `price` decimal(20,8) DEFAULT NULL COMMENT '车辆购买金额',
  `is_cold_chain_car` text COMMENT '是否为冷链车(0=否，1=是)',
  `is_wide_body` text COMMENT '是否宽体(0=否，1=是)',
  `axes` int DEFAULT NULL COMMENT '轴数',
  `retrofit_information` text COMMENT '改装信息',
  `vehicle_equipment` text COMMENT '车载装备',
  `temperature` text COMMENT '制冷区间',
  `temperature_probe` int DEFAULT NULL COMMENT '温度探头数',
  `pass_qualification_province_city_area` text COMMENT '通行资质区域（通行省/市/区）',
  `transport_certificate_deadline_date` text COMMENT '道路运输证有效期',
  `is_trailer` text COMMENT '是否挂车(0=机车，1=挂车)',
  `approve_time` text COMMENT '司机认证时间',
  `truck_approve_time` text COMMENT '车辆绑定时间',
  `carriage_brand` text COMMENT '车厢品牌',
  `cooling_power` text COMMENT '冷机功率',
  `cooler_type` text COMMENT '冷机类型 0非独立式 1独立式',
  `car_floor_air_uide` text COMMENT '车厢地板导风槽 0无 1有',
  `gps_brand` text COMMENT 'GPS品牌',
  `gps_brand_code` text COMMENT 'GPS品牌编码',
  `businessinsuranceendtime` text COMMENT '车辆商业险到期时间（个体车辆）',
  `car_kit_name` text COMMENT '车载装备名称',
  `load_accessories` text COMMENT '改装信息',
  `standard_truck_type` text COMMENT '标准车型'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='车辆基本属性纬度表';

CREATE TABLE `dim_pub_truck_tenant` (
  `source` text COMMENT '系统来源(1.0/2.0)',
  `truck_tenant_id` text COMMENT '车辆租户关系id',
  `truck_id` text COMMENT '车辆id',
  `license_plate_org` text COMMENT '原始车牌号',
  `license_plate` text COMMENT '车牌号',
  `father_tenant_id` text COMMENT '父级租户编码（大数据）',
  `father_tenant_name` text COMMENT '父级租户名称（大数据）',
  `father_short_name` text COMMENT '父级租户简称（大数据）',
  `settlement_tenant_id` text COMMENT '结算主体ID',
  `settlement_tenant_name` text COMMENT '结算主体名称',
  `tenant_id` text COMMENT '租户编码',
  `tenant_name` text COMMENT '租户名称',
  `supplier_id` text COMMENT '运力供应商id',
  `supplier_name` text COMMENT '运力供应商名称',
  `create_time` text COMMENT '创建时间',
  `update_time` text COMMENT '修改时间',
  `start_time` text COMMENT '合作开始时间',
  `end_time` text COMMENT '合作结束时间',
  `break_date` text COMMENT '违约日期',
  `type` text COMMENT '合作类型(自有/外请)',
  `state` text COMMENT '合作状态(启用/停用)',
  `is_enable` text COMMENT '启用/停用状态(启用/停用)',
  `remark` text COMMENT '备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='车辆合作关系主表';

CREATE TABLE `dws_ots_waybill_info_da` (
  `waybill_id` text COMMENT '运单ID',
  `waybill_code` text COMMENT '运单号',
  `shipping_order_code` text COMMENT '派车单号',
  `order_code` text COMMENT 'D订单号',
  `root_order_code` text COMMENT '根节点D订单号',
  `create_time` text COMMENT '运单创建时间',
  `root_order_create_time` text COMMENT '根订单创建时间',
  `root_order_time` text COMMENT '根订单下单时间 ',
  `start_transport_time` text COMMENT '派车单运输出发时间',
  `shipping_signing_time` text COMMENT '派车单签收时间',
  `waybill_signing_time` text COMMENT '运单签收时间',
  `check_income_time` text COMMENT '实际运输订单稽核时间',
  `reach_time` text COMMENT '要求送达时间 预计到货时间',
  `min_start_in` text COMMENT '进入取货地时间 电子围栏时间',
  `min_end_in` text COMMENT '进入卸货地时间 电子围栏时间',
  `start_time` text COMMENT ' 出发时间(预计出发时间) 预计取货时间',
  `customer_id` text COMMENT '根订单客户ID',
  `customer_code` text COMMENT '根订单客户code',
  `customer_name` text COMMENT '根订单客户名称',
  `un_social_creditcode` text COMMENT '统一社会信用代码',
  `un_social_creditname` text COMMENT '企业信用名称',
  `brand_code` text COMMENT '品牌编码',
  `brand_name` text COMMENT '品牌名称',
  `license_plate` text COMMENT '车牌号',
  `driver_code` text COMMENT '司机注册编码',
  `root_tenant_id` text COMMENT '跟节点租户ID',
  `tenant_id` text COMMENT '租户ID',
  `dep_station_code` text COMMENT '取货地站点编码',
  `dep_province_name` text COMMENT '取货地省份名称',
  `dep_city_name` text COMMENT '取货地城市名称',
  `des_station_code` text COMMENT '收货地站点编码',
  `des_province_name` text COMMENT '收货地省份名称',
  `des_city_name` text COMMENT '收货地城市名称',
  `temp_right_tag` text COMMENT '温度达标标签 合格/不合格/不参与评估',
  `is_gps_cover` text COMMENT '是否GPS覆盖',
  `is_48_audit` text COMMENT '是否48小时稽核',
  `is_on_time` text COMMENT '是否准时送达',
  `is_on_dep` text COMMENT '是否准时取货',
  `line_type` text COMMENT '线路类型 城配/干线',
  `mileage_type` text COMMENT '里程类型 超过200km/小于200km',
  `traff_num` text COMMENT '运输数量',
  `traff_weight` text COMMENT '运输重量',
  `traff_volume` text COMMENT '运输体积',
  `miles_total` text COMMENT '运输里程数',
  `is_ylz_zp` text COMMENT '是否运荔枝运营中心转派',
  `carrier_tenant_id` text COMMENT '派车单所属租户ID',
  `carry_tenant_id` text COMMENT '派车单指派承运商ID',
  `driver_supplier_code` text COMMENT '派车单运力承运商id',
  `parent_carrier_tenant_id` text COMMENT '上级派车单所属租户ID',
  `parent_driver_supplier_code` text COMMENT '上级派车单运力承运商id',
  `parent_carry_tenant_id` text COMMENT '上级派车单指派承运商ID',
  `dep_county_name` text COMMENT '取货地区县名称',
  `des_county_name` text COMMENT '收货地区名称',
  `project_code` text COMMENT '项目编码',
  `project_name` text COMMENT '项目名称',
  `shipping_company` text COMMENT '派车单所属分公司',
  `shipping_company_tenant_id` text COMMENT '派车单所属分公司租户id',
  `shipping_company_tenant_name` text COMMENT '派车单所属分公司租户名称',
  `shipping_1_company` text COMMENT '运荔枝首次转派派车单所属分公司',
  `shipping_1_company_tenant_id` text COMMENT '运荔枝首次转派派车单所属分公司租户id',
  `shipping_1_company_tenant_name` text COMMENT '运荔枝首次转派派车单所属分公司租户名称',
  `odr_deadline` text COMMENT '根订单截单时间',
  `shipping_create_time` text COMMENT '派车单创建时间',
  `driver_accept_time` text COMMENT '派车单司机接单时间',
  `plan_start_time` text COMMENT '派车单计划取货时间',
  `is_need_receipt` text COMMENT '是否需要回单',
  `receipt_date` text COMMENT '回单上传时间',
  `temp_eval_lowest` text COMMENT '温度考核最低值',
  `temp_eval_highest` text COMMENT '温度考核最高值',
  `shipping_order_temp_standard_rate` text COMMENT '温度达标率',
  `shipping_order_transport_min` text COMMENT '派车单运输总时长(分钟)',
  `temp_substandard_min` text COMMENT '温度不达标时长(分钟)',
  `transport_type` text COMMENT '派车单运输类型(干线/城配)',
  `driver_type` text COMMENT '司机类型',
  `income_amt` text COMMENT '收入金额',
  `income_amt_exclude_tax` text COMMENT '不含税收入金额',
  `order_cost` text COMMENT '成本金额',
  `order_cost_exclude_tax` text COMMENT '不含税成本金额',
  `order_actual_volume` text COMMENT '实际方量',
  `order_standard_load_volume` text COMMENT '准载方量',
  `project_group_code` text COMMENT '项目组ID',
  `project_group_name` text COMMENT '项目组名称',
  `parent_project_code` text COMMENT '上级项目ID',
  `parent_project_name` text COMMENT '上级项目名称',
  `parent_project_group_code` text COMMENT '上级项目组ID',
  `parent_project_group_name` text COMMENT '上级项目组名称',
  `root_project_code` text COMMENT '初始项目ID',
  `root_project_name` text COMMENT '初始项目名称',
  `root_project_group_code` text COMMENT '初始项目组ID',
  `root_project_group_name` text COMMENT '初始项目组名称',
  `own_customer_code` text COMMENT '订单客户code',
  `own_customer_name` text COMMENT '订单客户名称',
  `driver_accept_jz_time` text COMMENT '接单截止时间',
  `present_arrival_time` text COMMENT '到仓截止时间',
  `order_plan_start_time` text COMMENT '订单计划取货时间',
  `t_earliest_receiving_time` text COMMENT '最早收货时间',
  `t_latest_receiving_time` text COMMENT '最晚收货时间',
  `prj_order_cost` decimal(31,2) DEFAULT NULL COMMENT '项目成本金额',
  `prj_order_cost_exclude_tax` decimal(31,2) DEFAULT NULL COMMENT '不含税项目成本金额',
  `app_arrived_loading_time` text COMMENT 'app 定位碰撞取货地电子围栏的时间',
  `odr_channel` text COMMENT '订单来源',
  `create_shipper_time` text COMMENT '创建派车单时间',
  `shipping_mileage` text COMMENT '派车单里程',
  `shipping_status` text COMMENT '派车单状态',
  `tms_shipping_signing_time` text COMMENT '派车单签收时间(跟tms一致)',
  `project_user_id` text COMMENT '项目组负责人id',
  `project_user_name` text COMMENT '项目组负责人名称',
  `root_project_user_id` text COMMENT '初始项目组负责人id',
  `root_project_user_name` text COMMENT '初始项目组负责人名称',
  `business_user_id` text COMMENT '业务负责人id',
  `business_user_name` text COMMENT '业务负责人名称',
  `root_business_user_id` text COMMENT '初始项目业务负责人id',
  `root_business_user_name` text COMMENT '初始项目业务负责人名称',
  `max_start_out` text COMMENT '离开装货地时间',
  `max_end_out` text COMMENT '离开卸货地时间',
  `shipping_line_code` text COMMENT '派车单线路号',
  `plan_end_time` text COMMENT '派车单要求到达时间',
  `driver_arrive_time` text COMMENT '司机到仓时间',
  `root_shipping_order_code` text COMMENT '根节点派车单号',
  `root_waybill_code` text COMMENT '根节点运单号',
  `sign_type_name` text COMMENT '签收方式',
  `load_type_name` text COMMENT '装货方式',
  `gps_device_list` text COMMENT '设备供应商',
  `original_min_start_in` text COMMENT '进入取货地时间 电子围栏时间 原始'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='根节点订单对应运单信息';

CREATE TABLE `dws_station_portrait_index_sum_da` (
  `id` text COMMENT '站点id',
  `station_code` text COMMENT '站点编码',
  `station_name` text COMMENT '站点名称',
  `contacts` text COMMENT '联系人',
  `tel_phone` text COMMENT '联系电话',
  `tenant_id` text COMMENT '租户id',
  `tenant_name` text COMMENT '租户名称',
  `create_tenant_id` text COMMENT '创建租户id',
  `create_tenant_name` text COMMENT '创建租户姓名',
  `create_time` text COMMENT '创建时间',
  `update_time` text COMMENT '更新时间',
  `station_type_level_1` text COMMENT '站点类型：工厂、门店、仓库',
  `station_type_level_2` text COMMENT '站点行业类型',
  `station_type` text COMMENT '站点配送类型',
  `station_category` text COMMENT '站点类别',
  `enable_status` text COMMENT '启用状态：启用、停用',
  `province_name` text COMMENT '省份',
  `city_name` text COMMENT '城市',
  `county_name` text COMMENT '区县',
  `address` text COMMENT '具体地址',
  `longitude` decimal(20,8) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(20,8) DEFAULT NULL COMMENT '纬度',
  `station_code_poi` text COMMENT '统一站点code',
  `station_name_poi` text COMMENT '统一站点名称',
  `longitude_poi` decimal(20,8) DEFAULT NULL COMMENT '统一站点经度',
  `latitude_poi` decimal(20,8) DEFAULT NULL COMMENT '统一站点纬度',
  `is_poi_station` text COMMENT '是否统一站点：是、否',
  `order_cnt_total` int DEFAULT NULL COMMENT '累计派单量',
  `order_cnt_last365d` int DEFAULT NULL COMMENT '近一年派单量',
  `order_cnt_last90d` int DEFAULT NULL COMMENT '近90天派单量',
  `order_cnt_last30d` int DEFAULT NULL COMMENT '近30天派单量',
  `carrier_code_top5` text COMMENT '近90天常配送司机top5',
  `electric_fence_rate` decimal(20,8) DEFAULT NULL COMMENT '近30天电子围栏匹配率',
  `stay_time_avg` decimal(20,8) DEFAULT NULL COMMENT '近30天平均停留时长（装货/卸货）/分钟',
  `license_plate_top5` text COMMENT '近90天常配送车辆top5',
  `driver_code_top1` text COMMENT '近90天常配送司机top1',
  `truck_code_top1` text COMMENT '近90天常配送车辆top1',
  `station_source` text COMMENT '站点来源：内部/外部',
  `uniform_credit_code` text COMMENT '所属客户企业信用代码',
  `corp_name` text COMMENT '企业名称',
  `ck_cnt_last7d` int DEFAULT NULL COMMENT '近7天出入库单量',
  `ck_cnt_last30d` int DEFAULT NULL COMMENT '近30天出入库单量',
  `ck_cnt_last60d` int DEFAULT NULL COMMENT '近60天出入库单量',
  `ck_cnt_last365d` int DEFAULT NULL COMMENT '近365天出入库单量',
  `ck_cnt_total` int DEFAULT NULL COMMENT '累计出入库单量',
  `shipping_weight_last7d` decimal(20,8) DEFAULT NULL COMMENT '近7天运输重量/kg',
  `shipping_weight_last30d` decimal(20,8) DEFAULT NULL COMMENT '近30天运输重量/kg',
  `shipping_weight_last60d` decimal(20,8) DEFAULT NULL COMMENT '近60天运输重量/kg',
  `shipping_weight_last365d` decimal(20,8) DEFAULT NULL COMMENT '近365天运输重量/kg',
  `shipping_weight_total` decimal(20,8) DEFAULT NULL COMMENT '累计运输重量/kg',
  `goods_level1_last7d` int DEFAULT NULL COMMENT '近7天运输品类种类',
  `goods_level1_last30d` int DEFAULT NULL COMMENT '近30天运输品类种类',
  `goods_level1_last60d` int DEFAULT NULL COMMENT '近60天运输品类种类',
  `goods_level1_last365d` int DEFAULT NULL COMMENT '近365天运输品类种类',
  `goods_level1_total` int DEFAULT NULL COMMENT '累计天运输品类种类',
  `goods_last7d_top1` text COMMENT '近7天常配送品类',
  `goods_last30d_top1` text COMMENT '近30天常配送品类',
  `goods_last60d_top1` text COMMENT '近60天常配送品类',
  `goods_last365d_top1` text COMMENT '近365天常配送品类',
  `delete_status` text COMMENT '是否删除站点：是/否',
  `min_distance` decimal(20,8) DEFAULT NULL COMMENT '近30天取/卸点距站点平均距离',
  `time_quantum` text COMMENT '近30天常配送时间段',
  `time_quantum_max` text COMMENT '近30天最晚配送时间段',
  `time_quantum_min` text COMMENT '近30天最早配送时间段',
  `customer_group_short_name` text COMMENT '客户品牌',
  `create_date_min` text COMMENT '最早配送时间',
  `create_date_max` text COMMENT '最近配送时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='站点画像指标表';

CREATE TABLE `dws_truck_portrait_index_sum_da` (
  `truck_id` text COMMENT '车辆id',
  `license_plate` text COMMENT '车牌号',
  `license_plate_orig` text COMMENT '原始车牌号',
  `license_plate_color` text COMMENT '车牌颜色:黄色,绿色,蓝色,渐变绿,其他',
  `is_cold_chain_car` text COMMENT '是否冷链车',
  `temperature_probe` int DEFAULT NULL COMMENT '登记温度探头数',
  `oil_card_no` text COMMENT '油卡号',
  `province` text COMMENT '车牌归属省份',
  `city` text COMMENT '车牌归属城市',
  `truck_owning_name` text COMMENT '车辆所有人（行驶证上的挂靠公司或个人）',
  `charge_person_phone` text COMMENT '联系号码',
  `box_length_std` text COMMENT '车长',
  `consumption_type_name` text COMMENT '能耗类型:天然气,电动,汽油,柴油',
  `emission_std` text COMMENT '标准排放:国一,国二,国三,国四,国五,国六,国七,电动,其他',
  `ttl_truck_quantity` text COMMENT '车辆总质量(KG)',
  `user_status` text COMMENT '车辆使用状态:停用、启用',
  `temperature_area` text COMMENT '温区:单温,双温,三温',
  `truck_load_std` text COMMENT '标准载重(KG)',
  `register_date` text COMMENT '车辆注册登记日期',
  `paperwork_date` text COMMENT '发证日期',
  `ad_name` text COMMENT '车体广告公司名称',
  `truck_volume_std` text COMMENT '标准容积（立方米）',
  `is_bd_system` text COMMENT '北斗设备是否上报定位',
  `is_jy_system` text COMMENT '捷依设备是否上报定位',
  `is_e6_system` text COMMENT '易流设备是否上报定位',
  `gps_code` text COMMENT 'GPS终端编码（分子公司维护）',
  `gps_system_name` text COMMENT 'GPS系统（分子公司维护）',
  `max_gpstime_gps` text COMMENT 'GPS最近定位上传时间',
  `province_name_gps` text COMMENT 'GPS最近定位省份',
  `city_name_gps` text COMMENT 'GPS最近定位城市',
  `district_name_gps` text COMMENT 'GPS最近定位区县',
  `max_gpstime_app` text COMMENT 'APP最近定位上传时间',
  `province_name_app` text COMMENT 'APP最近定位省份',
  `city_name_app` text COMMENT 'APP最近定位城市',
  `district_name_app` text COMMENT 'APP最近定位区县',
  `day_num_total` int DEFAULT NULL COMMENT '累计运输天数',
  `order_num_total` int DEFAULT NULL COMMENT '累计运输单量',
  `miles_total` decimal(20,8) DEFAULT NULL COMMENT '累计运输里程数/公里',
  `driver_cnt_total` int DEFAULT NULL COMMENT '累计承运司机数',
  `dep_cities_total` int DEFAULT NULL COMMENT '累计出发城市数',
  `des_cities_total` int DEFAULT NULL COMMENT '累计到达城市数',
  `day_num_last90d` int DEFAULT NULL COMMENT '近90天运输天数',
  `order_num_last90d` int DEFAULT NULL COMMENT '近90天运输单量',
  `miles_last90d` decimal(20,8) DEFAULT NULL COMMENT '近90天运输里程数/公里',
  `dep_cities_last90d` int DEFAULT NULL COMMENT '近一年出发城市数',
  `des_cities_last90d` int DEFAULT NULL COMMENT '近一年到达城市数',
  `driver_cnt_last90d` int DEFAULT NULL COMMENT '近90天承运司机数',
  `driver_code_last` text COMMENT '最近承运司机',
  `driver_code_first` text COMMENT '最早承运司机',
  `create_time_last` text COMMENT '最近承运时间',
  `create_time_first` text COMMENT '最早承运时间',
  `cost_amt_total` decimal(20,8) DEFAULT NULL COMMENT '累计应付金额/元',
  `lines_total` int DEFAULT NULL COMMENT '累计线路数',
  `cost_amt_last90d` decimal(20,8) DEFAULT NULL COMMENT '近90天应付金额/元',
  `lines_last90d` int DEFAULT NULL COMMENT '近90天线路数',
  `day_num_last365d` int DEFAULT NULL COMMENT '近一年运输天数',
  `order_num_last365d` int DEFAULT NULL COMMENT '近一年运输单量',
  `miles_last365d` decimal(20,8) DEFAULT NULL COMMENT '近一年运输里程数/公里',
  `driver_cnt_last365d` int DEFAULT NULL COMMENT '近一年承运司机数',
  `dep_cities_last365d` int DEFAULT NULL COMMENT '近一年出发城市数',
  `des_cities_last365d` int DEFAULT NULL COMMENT '近一年到达城市数',
  `cost_amt_last365d` decimal(20,8) DEFAULT NULL COMMENT '近一年应付金额/元',
  `lines_last365d` int DEFAULT NULL COMMENT '近一年线路数',
  `day_num_last30d` int DEFAULT NULL COMMENT '近30天运输天数',
  `order_num_last30d` int DEFAULT NULL COMMENT '近30天运输单量',
  `miles_last30d` decimal(20,8) DEFAULT NULL COMMENT '近30天运输里程数/公里',
  `driver_cnt_last30d` int DEFAULT NULL COMMENT '近30天承运司机数',
  `dep_cities_last30d` int DEFAULT NULL COMMENT '近30天出发城市数',
  `des_cities_last30d` int DEFAULT NULL COMMENT '近30天到达城市数',
  `cost_amt_last30d` decimal(20,8) DEFAULT NULL COMMENT '近30天应付金额/元',
  `lines_last30d` int DEFAULT NULL COMMENT '近30天线路数',
  `dep_stations_total` int DEFAULT NULL COMMENT '累计出发站点数',
  `des_stations_total` int DEFAULT NULL COMMENT '累计到达站点数',
  `dep_stations_last365d` int DEFAULT NULL COMMENT '近365天出发站点数',
  `des_stations_last365d` int DEFAULT NULL COMMENT '近365天到达站点数',
  `dep_stations_last90d` int DEFAULT NULL COMMENT '近90天出发站点数',
  `des_stations_last90d` int DEFAULT NULL COMMENT '近90天到达站点数',
  `dep_stations_last30d` int DEFAULT NULL COMMENT '近30天出发站点数',
  `des_stations_last30d` int DEFAULT NULL COMMENT '近30天到达站点数',
  `is_gps_7d` text COMMENT '近7天是否有gps上报',
  `probe_num_max` int DEFAULT NULL COMMENT '近7天上报温度最多探头数',
  `probe_num_min` int DEFAULT NULL COMMENT '近7天上报温度最少探头数',
  `truck_type` text COMMENT '车型',
  `create_time` text COMMENT '创建时间',
  `review_status` text COMMENT '认证状态:已认证/未认证/无需认证',
  `stop_type` text COMMENT '停用类型：事故/无',
  `stop_reason` text COMMENT '停用原因',
  `transport_status` text COMMENT '运输状态:运输/空闲',
  `brand_model` text COMMENT '品牌型号',
  `is_trailer` text COMMENT '机车/挂车',
  `box_brand` text COMMENT '车厢品牌',
  `refrigerator_brand` text COMMENT '冷机品牌',
  `is_refrigerator_independence` text COMMENT '是否独立冷机:是/否',
  `temperature` text COMMENT '制冷区间',
  `truck_age` text COMMENT '车龄',
  `truck_tenant_type` text COMMENT '外请、自有、个体列表',
  `is_own` text COMMENT '是否自有车：是/否',
  `tenant_id` text COMMENT '自有车租户id',
  `tenant_name` text COMMENT '自有车租户名称',
  `father_tenant_id` text COMMENT '自有车父级租户id',
  `father_tenant_name` text COMMENT '自有车父级租户名称',
  `own_lon` text COMMENT '自有车分公司停靠经度',
  `own_lat` text COMMENT '自有车分公司停靠纬度',
  `own_addr` text COMMENT '自有车分公司停靠地址',
  `geo_region_name` text COMMENT '车牌所属大区',
  `company_list` text COMMENT '车辆绑定内部分公司列表',
  `car_floor_air_uide` text COMMENT '是否有导风槽',
  `cooling_power` text COMMENT '制冷量',
  `driver_name_last` text COMMENT '最近承运司机姓名',
  `driver_name_first` text COMMENT '最早承运司机姓名',
  `driver_phone_last` text COMMENT '最近承运司机电话',
  `driver_phone_first` text COMMENT '最早承运司机电话',
  `lines_top5` text COMMENT '近30天干线top5线路',
  `dep_city_top5` text COMMENT '近30天城配top5城市',
  `approve_time` text COMMENT '司机认证时间',
  `truck_type_setting_name` text COMMENT '配置车型',
  `is_transport_forage` text COMMENT '是否运输过饲料：是/否',
  `day_oil_consume_amount_ld10` decimal(20,8) DEFAULT NULL COMMENT '每日油卡消费金额_近10天',
  `day_etc_consume_amount_ld10` decimal(20,8) DEFAULT NULL COMMENT '每日ETC消费金额_近10天',
  `is_ylz_driver` text COMMENT '车牌被绑定个体司机是否运荔枝司机',
  `box_length_clear` text COMMENT '车型（温区&车长）',
  `company_trucktype` text COMMENT '鲜生活车辆类型列表：自有/外请/个体',
  `businessinsuranceendtime` text COMMENT '车辆商业险到期时间（个体车辆）',
  `axes` int DEFAULT NULL COMMENT '轴数',
  `truck_length` decimal(20,2) DEFAULT NULL COMMENT '外廓车长',
  `truck_wide` decimal(20,2) DEFAULT NULL COMMENT '外廓车宽',
  `truck_height` decimal(20,2) DEFAULT NULL COMMENT '外廓车高',
  `truck_quantity_type` text COMMENT '车辆大小分类',
  `gps_mileage_last30d` text COMMENT '近30天gps设备上报行驶里程',
  `gps_mileage_last90d` text COMMENT '近90天gps设备上报行驶里程',
  `gps_days_last30d` text COMMENT '近30天gps设备上报行驶天数',
  `gps_days_last90d` text COMMENT '近90天gps设备上报行驶天数',
  `gps_avgmileage_last30d` text COMMENT '近30天gps设备上报行驶平均里程/天',
  `gps_avgmileage_last90d` text COMMENT '近90天gps设备上报行驶平均里程/天',
  `is_wide_body` text COMMENT '是否宽体',
  `box_wide` decimal(20,2) DEFAULT NULL COMMENT '车厢宽',
  `box_height` decimal(20,2) DEFAULT NULL COMMENT '车厢高',
  `pass_qualification_province_name` text COMMENT '通行资质省name',
  `pass_qualification_city_name` text COMMENT '通行资质市name',
  `pass_qualification_area_name` text COMMENT '通行资质区name',
  `car_kit_name` text COMMENT '车载装备名称',
  `load_accessories` text COMMENT '改装信息',
  `standard_truck_type` text COMMENT '标准车型',
  `temperature_cnt` int DEFAULT NULL COMMENT '上报温度次数'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆画像指标表';